name: wekeo-earthkit
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - cartopy=0.24.0
  - earthkit-data=0.19.3
  - fsspec=2024.6.1
  - hda=2.34
  - ipykernel=6.29.5
  - ipython=8.29.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.3
  - pip=24.3.1
  - xarray=2024.5.0
  - zarr=2.18.3
  - pip:
      - earthkit-plots==0.6.1
